### PR TITLE
Black

### PR DESCRIPTION
**Pull request by stephane**
What do you think about using Black?

### CODE REVIEW

**Comment by JonasKs** [comment]
Hi, we’ve discussed this previously, and there’s a PR for it in #178. We decided to keep git history back then, since this library isn’t developed by me or Sondre, but transferred from Jobec. 

Running black removes all git blame, for not much gain. This library is at a maintenance stage, and not really actively developed(Azure specifically is in need of a big overhaul). If this changes, I think we’ll reconsider. Until then, I’m afraid I’ll deny this based on the previous discussion.

**Comment by stephane** [comment]
OK, thank you for your feedback.

**Comment by tim-schilling** [comment]
@JonasKs The concern about removing git blame is signficantly reduced by`.git-blame-ignore-revs`. I think it's worth discussing centered around that since the [original discussion mentioned it at the end](https://github.com/snok/django-auth-adfs/pull/178#issuecomment-907473269), but there wasn't a rebuttal.

**Comment by stephane** [comment]
> This library is at a maintenance stage, and not really actively developed(Azure specifically is in need of a big overhaul). If this changes, I think we’ll reconsider. Until then, I’m afraid I’ll deny this based on the previous discussion.

I'm a bit worried about this comment because I'm in the process to use this library in apps that require long term support.
Should I use a library based on https://github.com/AzureAD/microsoft-authentication-library-for-python instead?
Eg. https://github.com/AgileTek/django-azure-auth

**Comment by tim-schilling** [comment]
Maintenance doesn't mean a lack of support. I don't think any of the snok developers are going anywhere. However, it does mean new feature development is going to rely on the broader community to be the impetus.

**Comment by JonasKs** [comment]
^ this. Sorry if that was confusing. 

Security is my #1 priority. I've developed FastAPI-azure-auth, and I(almong others @snok) will continue to support and maintain this library. How ever, I'm no longer actively using Django, so I will personally not expand its features 😊

If someone decides to really work on its features/azure documentation and use cases, I will happily review and help. 

I can't really comment on the other libraries - one seem pretty unused and the official Azure one is very limited and not well integrated with Django and it's ORM(atleast wasn't before). 

You're in safe hands here - as you can see we are actively responding and reviewing MRs. I will probably look into making the middleware async 
 (or help/review), and with that maybe Black can be implemented - it'll be a pretty big rewrite.

**Comment by stephane** [comment]
Oh funny, I didn't know you work with snok, I was using snok/install-poetry` for CI until recently (now `pipx install poetry`).
On FastAPI side, I coded an app with FastAPI/SQLAlchemy last year but I've rewritten it in Django + django-ninja (pydantic) in March after serious concerns about concurrency and quality of support. I don't regret my choice BTW.

**Comment by JonasKs** [comment]
Snok is just an org with friends, collaborating on open source 😊

I understand, however the most important parts of FastAPI is pydantic and starlette, two projects I have full faith in. FastAPI is just a wrapper on top.

**Pull request closed without merging**
