### PR TITLE
Optimize update_user_groups to a fixed number of DB queries.

### PR DESCRIPTION
**Pull request by tim-schilling**
By using Django's `bulk_create` and set operations we can reduce the
time complexity of this function from two sorts to none and from
3 + (2ish * (claim_groups - existing _group_names) OR (claim_groups - existing _group_names) ) DB queries to a constant 3.

The downside of this approach is that the bulk_create operation
will not cause the `pre_save` and `post_save` signals to be raised
when creating the `Group` instances.

### CODE REVIEW

**Comment by JonasKs** [comment]
Hi @tim-schilling! I'll look into this later today. Thank you 🚀 

As a first thought I don't mind those signals not being kicked off, but I think the discussion of a major version bump should be had. What do you think?

Personally I don't believe the group creation signal is mentioned anywhere and not really officially supported, but I'd like to hear opinions. Efficiency on these things is a far more important concern to me. 

CC @sondrelg

**Comment by sondrelg** [comment]
Hmm this is a tough one.

I doubt there are many projects that rely on signals based off of these events. At the same time, if there are, the outcome could be pretty bad for them if they upgrade and this change flies under the radar. I think if we accept the change, we should probably bump major versions.

I'd normally advocate not having too high of a bar for major bumps - I think upgrading often is good generally, but maybe it's worth asking what the performance impact of the reduced time complexity is here. Have you benchmarked it @tim-schilling? If it's negligible in practice and we lose signals, maybe it wouldn't be a net benefit to users. I'd be happy to help try test it later this week if you want 🙂   

And it's been a while since I dived into the signals API, but is it possible to add these back manually? [This](https://github.com/django/django/blob/7119f40c9881666b6f9b5cf7df09ee1d21cc8344/django/db/models/base.py#L866) line from the Django project seems promising. If so, perhaps that would remove the downside.

**Comment by JonasKs** [comment]
> I think a major upgrade is reasonable. This change would be easy to miss and in the right circumstances have major impacts on an integration.

Alright, let's do that if you want to merge this, based on your benchmark findings. :+1:

**Comment by tim-schilling** [comment]
I'm closing this for now. I may revisit it in the future.

**Pull request closed without merging**
