### PR TITLE
Import changes for Django 4.0 compatibility

### PR DESCRIPTION
**Pull request by mcrowepfx**
Hello! I'm a grateful user of this package, and it's currently blocking me from updating several projects to Django 4.0. The only incompatibilities I see are in certain imports, and this PR should resolve them.

### CODE REVIEW

**Comment by sondrelg** [comment]
Thanks for this @mcrowepfx! Would you mind rebasing on master to pull in the Django 4.0 test matrix?

**Review by JonasKs — APPROVED** [review]
Thank you, looks great! :tada: Can be merged when you’ve done as Sondre asked and pipelines pass 😊

**Comment by mcrowepfx** [comment]
Sure, done.

**Comment by sondrelg** [comment]
I pushed 1ac87ce37ef0af83f9bf7e1e278adde38d5373d5 to the PR to see if that would resolve the remaining failing test - I think this is the way we should specify Django as a dependency. However, it looks like there are failing v3.8 and v4.0 test among other things. The v3.8 tests I suspect need to be fixed, while the v4 I'm not sure about yet - it could be that we need to fix the pyproject.toml somehow. Can look at it more tomorrow. Feel free to take a look meanwhile @JonasKs

**Pull request merged**
