### PR TITLE
Add version setting and fix white space issue

### PR DESCRIPTION
**Pull request by jatindergit**

### CODE REVIEW

**Comment by jatindergit** [comment]
@JonasKs Please merge

**Comment by JonasKs** [comment]
I’m on vacation. This will probably have to wait until I’m back. 🏖️

**Comment by jatindergit** [comment]
> s will probably have to wait until I’m

When you are coming back

**Comment by JonasKs** [comment]
This looks good. :tada: I'd love a test for the setting, though. Are you able to provide this, or do you want assistance?

**Comment by jatindergit** [comment]
> the sett

You can test it and please let me know if anything is needed

**Comment by JonasKs** [comment]
Alright, I'll look into this. Please ensure I have access to your branch (I think you can use a checkbox on this merge request to allow maintainers of this repo to edit your code, but if not, giving me directly access on your fork is an option)

**Comment by jatindergit** [comment]
**Allow edits by maintainers** is already checked

**Comment by jatindergit** [comment]
@JonasKs Please let know when you will do this. I really need this. This will be a great help if you do this asap. Thanks in advance :)

**Comment by JonasKs** [comment]
I'll try to do it today or tomorrow. :)

**Comment by JonasKs** [comment]
Please fix merge issues first.   

Remember that it's always best to create feature branches and make PRs from them, instead of your own master.

**Comment by jatindergit** [comment]
@JonasKs Done. Sorry I am doing this first time

**Comment by JonasKs** [comment]
No worries - only way to learn! 🎉 Unfortunately I won't have time tonight, but I'll probably have time tomorrow.

**Comment by JonasKs** [comment]
Hi @jatindergit . I've written a few tests and did a few minor changes. I've also went ahead and merged the change.

Thank you for your contribution! :tada: 

You can expect a new release today.

**Comment by JonasKs** [comment]
It's available as version `1.7.0` on [PyPI](https://pypi.org/project/django-auth-adfs/) now.

**Pull request merged**
