### PR TITLE
Fixed attribute debug logging

### PR DESCRIPTION
**Pull request by joachimBurket**
User and flag were swapped in the log.
(I know it's a very small change but it allows me to practice pull requests 😄)

### CODE REVIEW

**Review by sondrelg — APPROVED** [review]
LGTM 🙂 I'll let @JonasKs merge

**Comment by JonasKs** [comment]
Awesome! Thank you. 🎉

**Review by JonasKs — APPROVED** [review]

**Comment by joachimBurket** [comment]
You're welcome! :)

**Comment by sondrelg** [comment]
Did you accidentally close this @joachimBurket? 😄

**Comment by joachimBurket** [comment]
Oups I think I closed it prematurely 😆 I'll wait for the merge this time hahah

**Pull request merged**
