### PR TITLE
Allow more than 100 group items to be fetched from MS Graph API

### PR DESCRIPTION
**Pull request by freyp577**
Use of MS Graph API to fetch group information for the user imposes a limitation of max 100 items returned per API request
so when there are more than 100 groups, the request needs to be repeated with the API call using the odata.nextLink value returned in the current result

see Microsoft Graph API Result Size Limit for details

### CODE REVIEW

**Comment by freyp577** [comment]
Fix for https://github.com/snok/django-auth-adfs/issues/272

**Comment by tim-schilling** [comment]
My concern once is that we're now at 1 to N requests to authenticate a user. If we're building something for folks who have hundreds of groups per user, do we take it to the next step and give them the ability to [search and filter](https://learn.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&tabs=http#optional-query-parameters)?

**Comment by freyp577** [comment]
@tim-schilling 
good point, actually we need only a couple of groups from the > 200 groups we get from our AD onpremise / azureAD combination - they all have a certain prefix (_EDB) so if there were filtering it would be useful here

note also that we have solved this issue picking our groups by subclassing some functionality django-auth-adfs provides
as we not only need to filter but also normalize the group names was they do not match 1:1 between our AD/azureAD and Django worlds

So it is your decision if you accept this as improvement, or replace it by a better approach that is more flexible.

**Comment by vidhuUC** [comment]
Can we just change the graph_url to  ` "https://{}/v1.0/me/transitiveMemberOf/microsoft.graph.group?$count=true&$top=999".format(
            provider_config.msgraph_endpoint
        )`
  to get all groups for User

**Comment by tim-schilling** [comment]
@freyp577 I didn't like that we couldn't even support the bare minimum so I wrote #352. If you still feel like the solution you have is better, please let us know and we'll revisit this.

**Pull request closed without merging**
