### PR TITLE
Implementation, tests and docs of pull request #104

### PR DESCRIPTION
**Pull request by joachimBurket**

### CODE REVIEW

**Comment by JonasKs** [comment]
Thank you!! 
I'm out of town for a few days, but I'll check it when I get home.  🎉 

@sondrelg , any comments?😊

**Comment by joachimBurket** [comment]
@JonasKs ping ?

**Comment by JonasKs** [comment]
I'm sorry, I totally forgot about this.

I'll check it out tonight and release before the weekend.

**Comment by joachimBurket** [comment]
No worry I also forgot it 😅 
Thanks :)

**Comment by JonasKs** [comment]
Looks good to me! :tada: 

Could you please bump version like [we did here](https://github.com/snok/django-auth-adfs/pull/167/files)? Otherwise I'll have to wait until Monday to merge and release, but that's okay if you want to wait. :blush:

**Comment by JonasKs** [comment]
Thank you! Unfortunately I tagged the wrong PR (#104) instead of #172 in the release notes. I'm sorry about that.

**Comment by joachimBurket** [comment]
No worry for the tag and thanks a lot for the release! :)

**Pull request merged**
