### PR TITLE
Allow username matching field to be configured.

### PR DESCRIPTION
**Pull request by simeon-walker**
Hello. Our Azure AD does not have the winaccountname or sAMAccountName available to match against username in our Django User table. We do have fields that can be matched, one being the SID. This patch allows the match field to be configured so you can lookup the Django User based on what claims you have available. Hope it's useful.

### CODE REVIEW

**Comment by simeon-walker** [comment]
Rookie error in the code path we can't use, will update.

**Comment by JonasKs** [comment]
You can just use [this](https://django-auth-adfs.readthedocs.io/en/latest/settings_ref.html#username-claim) setting and change it to `SID`.

**Comment by simeon-walker** [comment]
> You can just use [this](https://django-auth-adfs.readthedocs.io/en/latest/settings_ref.html#username-claim) setting and change it to `SID`.

Yes, but it would still try and match against the model USERNAME_FIELD. It needs to lookup against another field, SID in our case.

**Comment by JonasKs** [comment]
Ahaaa, I'm sorry, I misread it. Multitasking isn't my strong side. 

Could you add a test for this? :)

**Comment by JonasKs** [comment]
Hi, could you add a test or two? 😄

**Comment by simeon-walker** [comment]
> Hi, could you add a test or two? smile

Hi, yes, sorry haven't got back to it yet. Need to figure out what to test.

**Comment by JonasKs** [comment]
Any status? ☺️

**Comment by sondrelg** [comment]
Closing this due to inactivity. Feel free to re-open with a test @simeon-walker 🙂

**Pull request closed without merging**
