### PR TITLE
Handle scope and also removing resource when VERSION=v2.0

### PR DESCRIPTION
**Pull request by mwigh**
Handle scope when VERSION=v2.0

### CODE REVIEW

**Comment by tim-schilling** [comment]
Thank you for the change! We'll need a corresponding test for this too.

**Comment by mwigh** [comment]
Can look on that coming days, had some issues with poetry today.

**Comment by JonasKs** [comment]
Thank you so much, this should solve #198. 

Looks good to me 🎉

**Comment by JonasKs** [comment]
.. some tests fail, but I don't think that it's related to this PR. I'll try to look into it this weekend. We should also drop Python3.6 support.

**Review by JonasKs — APPROVED** [review]

**Comment by JonasKs** [comment]
Fixed pipelines, bumped version and removed Python3.6 support.

@tim-schilling @sondrelg , any comments? 😊

**Comment by JonasKs** [comment]
Thank you so much! 😊 


This will be released on PyPI any minute now. 

Github release found here: https://github.com/snok/django-auth-adfs/releases/tag/1.9.6

**Pull request merged**
