### PR TITLE
Disambiguate debug messages of auth backends

### PR DESCRIPTION
**Pull request by stephane**

### CODE REVIEW

**Comment by tim-schilling** [comment]
I believe the reason this is called "authorization code" is because AD passes back the value with for `code` querystring key that ends up in the `access_token` parameter in the backend class.

**Comment by stephane** [comment]
I understand, I saw that when I created my PR but I think it's more important to inform the user about the source of the log[1] so he will be able to check it is using the right backend.
Another way would be to prefix the message with the backend name.

BTW some messages are prefixed with `django_auth_adfs `, it creates duplicates with the proposed logging config ex. `django_auth_adfs django_auth_adfs loaded settings from ADFS server.`

[1] without using advanced logger settings to output the function name

**Comment by tim-schilling** [comment]
Ah, I better understand your use case. I'm good with this change, but I'd like another maintainer to chime in before merging.

**Comment by JonasKs** [comment]
> BTW some messages are prefixed wit…

I’m okay fixing these too!

**Comment by stephane** [comment]
> > BTW some messages are prefixed wit…
> 
> I’m okay fixing these too!

Do you want an updated PR to include that?

**Comment by JonasKs** [comment]
Sure, that would be nice😊 If you’d like to update the version in `pyproject.toml` and `__init__.py` it makes releasing a new version easier for us too😊

**Comment by tim-schilling** [comment]
@stephane does this have all the changes you intended to make?

**Comment by stephane** [comment]
I tried to use metadata to import version from `pyproject.toml` w/o success (not the duplicate still there).
Anyway I prefer to leave you bump the version number after merge.

**Comment by tim-schilling** [comment]
Thank you for the PR and edits!

**Pull request merged**
